### ISSUE TITLE
Files built without respecting LDFLAGS have been detected

### ISSUE THREAD

**Issue by blshkv** [radare/radare2-capstone#3]
This is similar with https://github.com/aquynh/capstone/issues/57

   usr/lib/radare2/0.9.7/asm_arm_cs.so
   usr/lib/radare2/0.9.7/asm_x86_cs.so
   usr/lib/radare2/0.9.7/asm_mips_cs.so
   usr/lib/radare2/0.9.7/asm_ppc_cs.so
   usr/lib/radare2/0.9.7/anal_x86_cs.so
   usr/lib/radare2/0.9.7/anal_arm_cs.so
   usr/lib/radare2/0.9.7/anal_mips_cs.so
   usr/lib/radare2/0.9.7/anal_ppc_cs.so

**Comment by radare** [comment]
This repo is not maintained anymore. The latest r2 git repo already contains those plugins

**Comment by radare** [comment]
LDFLAGS is respected when building capstone inside r2 and when building 
the plugins. We are currently working on 0.9.8git version, can you 
confirm this is still happening on git version?

thanks

**Comment by blshkv** [comment]
We fixed capstone in the bug #57 and it builds from git just fine. I didn't know that radare2-capstone is not maintained and I wanted to help fix it too.
