### ISSUE TITLE
hard-coded /usr/lib path

### ISSUE THREAD

**Issue by blshkv** [radare/radare2-capstone#4]
This is similar with https://github.com/aquynh/capstone/issues/51

For more build env, see https://code.google.com/p/pentoo/issues/detail?id=278

**Comment by radare** [comment]
This repo is not maintained anymore. The latest r2 git repo already contains those plugins

**Comment by blshkv** [comment]
Please release a next stable version then ... We rely on releases, not a random git version.

**Comment by blshkv** [comment]
oh, I just found a new version hidden under "***" .. so please ignore my comment
